# Account.onCreateAvatarResult
RESULT_CREATE_AVATAR_SUCCESS = 0
RESULT_CREATE_AVATAR_TOP_LIMIT = 1

# Avatar.client.onRetCode
ROOM_DOES_NOT_EXIST = 1
HALL_DOES_NOT_EXIST = 3

ALREADY_IN_A_ROOM = 101
ALREADY_IN_A_MATCH = 102
NOT_IN_A_MATCH = 103
NOT_IN_A_ROOM = 104
MATCH_ROOM_NO_ONE_FOUND = 105
EVENT_REQ_UNDO_MOVE_FALSE = 106
EVENT_RSP_UNDO_MOVE_FALSE = 107
EVENT_REQ_PEACE_FALSE = 108
EVENT_RSP_PEACE_FALSE = 109

ROOM_UP_LIMIT = 201
ROOM_TURN_OCCUPY = 202
ROOM_SEAT_WRONG = 203
ROOM_ALREADY_STARTED = 204
ROOM_NOT_ALL_PREPARED = 205
ROOM_NOT_COMPLETED = 206
ROOM_BOARD_NOT_READY = 207
ROOM_SET_PREPARED_EXIST = 208
ROOM_SET_PREPARED_STARTED = 209
ROOM_ENTER_ONLY_FOR_WATCHER = 210
ROOM_ENTER_CONDITION_NOT_MET = 211
ROOM_ENTER_AUTH_FAILED = 212


# Avatar.client.onLeaveRoom
# Avatar.onLeaveRoom
ROOM_LEAVE_REQ = 1
ROOM_LEAVE_DESTROYED_NO_PLAYERS = 2
ROOM_LEAVE_DESTROYED_NO_FOUNDER = 3
ROOM_LEAVE_DISCONNECT = 4
ROOM_LEAVE_CONDITION_NOT_MET = 5
ROOM_LEAVE_CHANGE_TABLE = 6
